### ISSUE TITLE
MVPs

### ISSUE THREAD

**Issue by cindyytong** [lifesscholar/Greatreads#1]
Hi Neev: Great work! Some nits

- [x] MVP 3 Books:
- add bullet point that users can view book show pages 
- remove this bullet since it is handled in bookshelves "Logged in users can save books to their bookshelves" 

-[ ] Reviews add the following bullet: An average review score for the book will be displayed as well as the total number of reviews

-[ ] For bonus feature tags: add bullet for tags and searching across tags

**Comment by lifesscholar** [comment]
Thank you Cindy! I have made those changes
