### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by cindyytong** [lifesscholar/Greatreads#2]
- [x] Users:
- remove bookshelf_ids

-[ ] Books:
- remove uniqueness on author and title b/c an author can have many books. We could have 2+ books with same title but we want to make sure the combo of author and book title are unique.  

-[ ] Bookshelves:
- remove "book_ids" 
- consider renaming to Shelf so you don't have to write book all the time :)

**Comment by lifesscholar** [comment]
Thank you Cindy! I made those changes
